import { auth } from './firebase.js';
import { getWalletBalance, giftTokens } from './wallet.js';
import { openSheet } from './sheet.js';
import { icon } from './icons.js';
const packs=[10,30,50,100,200,500,1000,2000];
const usd=n=>`$${(n/100).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const escape=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export async function openGiftSheet({toUID,toName='Member',toPhoto=''}) {
  const fromUID=auth.currentUser?.uid; if(!fromUID) throw new Error('Sign in to send a gift.');
  let balance; try { balance=await getWalletBalance(fromUID); } catch(error) { console.error('Could not load gift balance',error); throw new Error('Could not load your wallet balance.'); }
  const avatar=toPhoto?`<img src="${escape(toPhoto)}" alt="" style="width:42px;height:42px;border-radius:50%;object-fit:cover">`:`<div style="width:42px;height:42px;border-radius:50%;background:var(--surface2);display:grid;place-items:center;color:var(--gold)">${icon('user')}</div>`;
  const sheet=openSheet({label:`Send token gift to ${toName}`,content:`<div style="display:flex;gap:10px;align-items:center;padding-right:44px"><div>${avatar}</div><div><h2 style="margin:0">Send a gift</h2><div class="muted">To ${escape(toName)}</div></div></div><p class="muted" style="margin:1rem 0 .65rem">Your balance: <b id="giftBalance">${balance.toLocaleString()} tokens</b></p><div class="gift-amounts" id="giftAmounts"></div><p class="muted" id="giftAfford" style="font-size:12px;margin:.65rem 0 0"></p><div class="gift-custom" id="giftCustom" hidden><label for="giftCustomAmount">Custom amount</label><input id="giftCustomAmount" type="text" inputmode="numeric" autocomplete="off" placeholder="Minimum 10 tokens"/></div><div class="gift-error" id="giftError" role="alert"></div><label for="giftNote">Add a note <span class="muted">(optional)</span></label><input id="giftNote" maxlength="80" placeholder="Add a note"/><button class="btn btn-gold btn-full" id="giftSend" disabled style="margin-top:1rem;min-height:44px"></button>`});
  const root=sheet.element, amounts=root.querySelector('#giftAmounts'), custom=root.querySelector('#giftCustom'), input=root.querySelector('#giftCustomAmount'), error=root.querySelector('#giftError'), send=root.querySelector('#giftSend'); let selected=0;
  amounts.innerHTML=[...packs,'Custom'].map(n=>`<button class="gift-chip" data-amount="${n==='Custom'?'custom':n}" ${n!=='Custom'&&n>balance?'disabled':''}>${n==='Custom'?'Custom':`<b>${n.toLocaleString()}</b><small>${usd(n)}</small>`}</button>`).join('');
  const validate=()=>{let value=selected==='custom'?Number(input.value):Number(selected); let msg=''; if(selected==='custom'){if(!/^\d+$/.test(input.value)) msg='Enter a whole number of tokens.'; else if(value<10) msg='A gift must be at least 10 tokens.'; else if(value>balance) msg='That amount is more than your balance.';} if(value>balance)msg='That amount is more than your balance.'; const valid=Number.isInteger(value)&&value>=10&&value<=balance&&!msg; error.textContent=msg; send.disabled=!valid; send.innerHTML=valid?`Send ${value.toLocaleString()} tokens · ${usd(value)}`:'Choose an amount'; return valid?value:0};
  amounts.onclick=e=>{const b=e.target.closest('.gift-chip');if(!b||b.disabled)return; selected=b.dataset.amount==='custom'?'custom':Number(b.dataset.amount); root.querySelectorAll('.gift-chip').forEach(x=>x.classList.toggle('selected',x===b)); custom.hidden=selected!=='custom'; if(selected==='custom')input.focus(); validate();}; input.oninput=validate;
  if(packs.some(n=>n>balance)) root.querySelector('#giftAfford').innerHTML=`Some amounts are unavailable. <a href="/account/payment/?purpose=tokens">Buy tokens</a>`;
  send.onclick=async()=>{const amount=validate();if(!amount)return;send.disabled=true;send.innerHTML=`<span class="dv-spinner"></span> Sending…`;try{await giftTokens(fromUID,toUID,amount,root.querySelector('#giftNote').value.trim());sheet.close(); const {showSuccess}=await import('./dialog.js');showSuccess(`Gift sent — ${amount.toLocaleString()} tokens to ${toName}`)}catch(err){console.error('Gift failed',err);error.textContent=err.message||'Could not send gift.';send.disabled=false;validate()}};
}
