const { json, parseBody, preflight } = require('./_helpers');
const { sendPushToUser } = require('./send-push');
let db, firebase;
function admin(){ if(firebase)return firebase; firebase=require('firebase-admin'); if(!firebase.apps.length) firebase.initializeApp({credential:process.env.FIREBASE_SERVICE_ACCOUNT?firebase.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT)):firebase.credential.applicationDefault()}); db=firebase.firestore(); return firebase; }
async function callerUID(event){const token=(event.headers.authorization||event.headers.Authorization||'').replace(/^Bearer\s+/i,'');if(!token)throw Object.assign(new Error('Sign in required.'),{status:401});return admin().auth().verifyIdToken(token);}
function matchId(a,b){return [a,b].sort().join('_')}
function vault(user){const s=user.subscription||{};return (s.plan||user.plan)==='vault'&&s.status==='active'&&(!s.nextBillingDate||new Date(s.nextBillingDate)>=new Date());}
async function daily(path, body){const r=await fetch(`https://api.daily.co/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${process.env.DAILY_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Could not create video call room.');return r.json();}
async function charge(uid){let balance;await db.runTransaction(async tx=>{const ref=db.collection('users').doc(uid),snap=await tx.get(ref),n=Number(snap.data()?.walletBalance||0);if(n<50)throw Object.assign(new Error('insufficient_tokens'),{status:402,balance:n});balance=n-50;tx.update(ref,{walletBalance:balance});tx.set(ref.collection('walletTransactions').doc(),{type:'call_charge',amount:-50,note:'Video call initiated',createdAt:admin().firestore.FieldValue.serverTimestamp(),status:'completed'});});return balance;}
exports.handler=async event=>{if(preflight(event))return preflight(event);try{if(event.httpMethod!=='POST')return json(405,{error:'POST required'});const user=await callerUID(event),body=parseBody(event),adminCall=body.adminCall===true, toUID=body.toUID, action=event.queryStringParameters?.action||body.action;if(action==='join'){const invite=await db.collection('videoCallInvites').doc(body.inviteId).get();if(!invite.exists||invite.data().toUID!==user.uid)throw Object.assign(new Error('Invite not found'),{status:403});const token=await daily('meeting-tokens',{properties:{room_name:invite.data().roomName,exp:Math.floor(Date.now()/1000)+1800}});return json(200,{roomURL:`https://datevault.daily.co/${invite.data().roomName}`,token:token.token});}const [from,to]=await Promise.all([db.collection('users').doc(user.uid).get(),db.collection('users').doc(toUID).get()]);if(!to.exists)throw new Error('Member not found');if(adminCall){if(from.data()?.role!=='admin')throw Object.assign(new Error('Admin access required'),{status:403});}else{if(!vault(from.data()))throw Object.assign(new Error('Vault access required'),{status:403});if(!(await db.collection('matches').doc(matchId(user.uid,toUID)).get()).exists)throw Object.assign(new Error('You can only call matches.'),{status:403});}let balance=null;if(!adminCall)balance=await charge(user.uid);try{const room=await daily('rooms',{name:`dv-${matchId(user.uid,toUID)}-${Date.now()}`,properties:{exp:Math.floor(Date.now()/1000)+1800,enable_screenshare:false,max_participants:2,eject_at_room_exp:true}}),token=await daily('meeting-tokens',{properties:{room_name:room.name,exp:Math.floor(Date.now()/1000)+1800}}),ref=db.collection('videoCallInvites').doc();await ref.set({fromUID:adminCall?'admin':user.uid,toUID,matchId:matchId(user.uid,toUID),roomName:room.name,createdAt:admin().firestore.FieldValue.serverTimestamp(),expiresAt:admin().firestore.Timestamp.fromMillis(Date.now()+30000),status:'ringing',type:adminCall?'admin_call':'member_call'});sendPushToUser({toUID,title:'Incoming video call',body:`${adminCall?'DateVault Team':(from.data()?.displayName||from.data()?.name||'A member')} is calling you`,url:'/app/chat/'}).catch(error=>console.error('Could not send call push notification',error));return json(200,{inviteId:ref.id,roomURL:room.url,token:token.token,tokenBalance:balance});}catch(e){if(!adminCall)await db.collection('users').doc(user.uid).update({walletBalance:admin().firestore.FieldValue.increment(50)});throw e;}}catch(e){return json(e.status||400,{error:e.message,balance:e.balance});}};
